name: Tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
env:
  MYSQL_URL: ${{ secrets.DATABASE_URL }}
  MYSQL_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      - name: Shutdown Ubuntu MySQL (SUDO)
          run: sudo service mysql stop
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: recipes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name:  Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 0.0.0.0 --port 3306 -uroot -ppassword -e "SHOW DATABASES;"
      - name: Verify MariaDB connection
        run: mysql --host 0.0.0.0 --port 3306 -uroot -ppassword < .docker/setup.sql
      - name: Run tests
        env:
          MYSQL_URL: "mysql2://root:password@0.0.0.0:3306/recipes"
          MYSQL_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: sbt clean coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
