name: Scala CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MYSQL_URL: ${{secret.MYSQL_URL}}
      MYSQL_USERNAME: ${{secret.MYSQL_USERNAME}}
      MYSQL_PASSWORD: ${{MYSQL_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
      - name: Build docker-compose
        - run: docker-compose up -d
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck